### ISSUE TITLE
questions related to simulator new configuration

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldfoundation/simulator#21]
- Question 1 
The cloud unit prices were previously array and in all cases it was (3) now we got three different values to it 
![image](https://user-images.githubusercontent.com/46320202/88098101-8335d700-cb99-11ea-90a4-a667670da841.png)
![image](https://user-images.githubusercontent.com/46320202/88098112-8a5ce500-cb99-11ea-913f-2b4e09dd9645.png)

these values already related to actual values in code 
![image](https://user-images.githubusercontent.com/46320202/88098286-d14ada80-cb99-11ea-8fdd-7a9f23198227.png)
so I am not sure low, mid ... related  cu,us and nu in the code and if so, what is the value of cloud unit price now or i am getting something wrong.

- Question 2
in the new configuration, there is no overhead 
![image](https://user-images.githubusercontent.com/46320202/88099225-2c310180-cb9b-11ea-81ab-2723d4619c4b.png)
in the old there was overhead
![image](https://user-images.githubusercontent.com/46320202/88099261-3a7f1d80-cb9b-11ea-8fd0-2f5bb65ecae4.png)

**Comment by abom** [comment]
A1:

This will be mapped to prices here:
https://github.com/threefoldfoundation/simulator/blob/af787ce1aa0856db2f2fbbc56d096fcd16655c79/src/simulator/SimulatorFactory.cr#L137-L160

**Comment by abom** [comment]
A2:

For now, let's append overhead (before switch) like the current implementation

![Screenshot from 2020-07-22 12-42-02](https://user-images.githubusercontent.com/511438/88167255-d307b300-cc18-11ea-9e9e-d8aea67da3b2.png)

**Comment by abom** [comment]
A3:

We assume it's a bom device of this device_normalized component, something like
```yaml
default:
    - device_nromalized: <nr_nodes_start>
````

`nr_nodes_start` is defined at `environemnt_default.yml`:

```yaml
simulation:
  # first batch of nodes added is 1500 nodes
  # each node is +-4.5k usd (check the bill of material sheet)
  # and we start the simulation with 800m tokens already farmed by the TF Farmers
  nr_nodes_start: 1500
```
